development:
    base_query: "select id, name, label, value from websites"

    where_clause: "where id in"
    
    # comma separated field names
    field_names: 'id, name, label, value'

    # comma separated field names
    field_friendly_names: [Id, Name, Label, Value]

    uri_field_name: 'Id'
test:
    query: select name from websites
production:
    query: select name from websites